"""users table

Revision ID: 02185728c145
Revises: 
Create Date: 2020-11-15 18:06:30.036196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02185728c145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userss_email'), 'userss', ['email'], unique=True)
    op.create_index(op.f('ix_userss_username'), 'userss', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userss_username'), table_name='userss')
    op.drop_index(op.f('ix_userss_email'), table_name='userss')
    op.drop_table('userss')
    # ### end Alembic commands ###
